language: python
python:
  - "3.4"
install:
  - "pip install -r requirements.txt"
script:
  - "cp wysadzulice_pl/secrets.py.example wysadzulice_pl/secrets.py"
  - "pep8 --exclude='wysadzulice/migrations/*' ."
  - "coverage run --source=wysadzulice manage.py test"
after_success:
  - "codecov"
